spring:
  application:
    name: testsecurity

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bankdb
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

# Encryption Configuration
encryption:
  # AES Key (256-bit) - Dùng để mã hóa dữ liệu khi lưu vào database
  # Generate key: java -cp target/classes com.example.testsecurity.util.AesKeyGenerator
  aes:
    key: MLEQ/ogfPk0z7ZtutxRWRodUqu48mEvorrUWagjq5Sc=
  # RSA Keys (2048-bit) - Dùng để mã hóa dữ liệu khi truyền giữa các services
  # Generate keys: java -cp target/classes com.example.testsecurity.util.RsaKeyGenerator
  rsa:
    public-key: ${RSA_PUBLIC_KEY:MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA7Kxnmd3XkyIk4xHm5iBf7bj7YFVXNYnwyB6tuM9+F2rB3ub0sTsLWKqEeT29B2j2f2/klY9YUF6/JuH0iEXgJQz4NclQNIi0k5Z5LDGc3Dnf1Oxl2t2DcWj2F+CuCERmRxCnbrKOsOH/LxZXnjzRDTTVTxIF4QP0lh7M49ZDyFvo1GJ1iks4BaY8G22ciYF/+bBVkOTKsu9wMp6A2+NDetEu0HMBLGLOepgirDHWd21xl2fC+0lH0EVmocP5jm8tQNQjs3DXIaMGsdELqddvF87FHG78lPklbZZ9P8iitr6EMv5ysi7Bn+1GLV3MlYc3O2mpiOQgt6IvJxvInjh2RQIDAQAB}
    private-key: ${RSA_PRIVATE_KEY:MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDsrGeZ3deTIiTjEebmIF/tuPtgVVc1ifDIHq24z34XasHe5vSxOwtYqoR5Pb0HaPZ/b+SVj1hQXr8m4fSIReAlDPg1yVA0iLSTlnksMZzcOd/U7GXa3YNxaPYX4K4IRGZHEKduso6w4f8vFleePNENNNVPEgXhA/SWHszj1kPIW+jUYnWKSzgFpjwbbZyJgX/5sFWQ5Mqy73AynoDb40N60S7QcwEsYs56mCKsMdZ3bXGXZ8L7SUfQRWahw/mOby1A1COzcNchowax0Qup128XzsUcbvyU+SVtln0/yKK2voQy/nKyLsGf7UYtXcyVhzc7aamI5CC3oi8nG8ieOHZFAgMBAAECggEAUd6vtd+yN2Drzqq+K2QOmw7O0jujP894Pdmy8YfBT/trlh5hjb9lhOXzjncnYR1Ti7Daq0vbWm30BNDMBKnbSCXM5No/RvT1NkqqnvmIj/vrLF4cO9I9qmkLHCZqPUzf7nxZ1uaoipKa8iBx7biO/lkE4uXSp8x0+ssryDKx3ugV4zuJnYQUe0h1ydtFbOUrMINcot5fUO5DLwFt9+/XDHx1iqRI44BkJ4KO4dcTcGI+kxuUWGH4cU4JUOI+H7zMCPt7WbSgovNHsox3jTGZFzi/T6Fu0ibJef77j6M3NCrSXWrx9RSSnsIadRX8BzcdMGPknUM2owW4GaLBrcxuPwKBgQD+8R5QBqMPtTY2Bg6OeJdF79PEEsdIkRkao25ABiams9DVbxzo2/wVjkPVnyw/0x3xh7vwp2H7JkhQAbwsa5bweXX5fE73A+WWmcUrRFO9dljbZCNo8M/+83IcN+tuq+QWHvf1EQh3TVAyRJB8Aivs/1HYVHc+ZGfj53IdF94YowKBgQDtp+AsNb/td2bqcTXNI7/RX+hbD8SI8Y/qKtsfIRG6Q2Vvydj/4sMV0GDxnndH6EmeEmnXfRxhZigVBFJRiZfnEss/4Jmy6C0k9R+WAd7L0zRg1k6hvohQXjYXF/gjEk+7q4BNG0knGq5F+4fiIUIuzlCd8SpM+6Wf/5NRtiyb9wKBgHWrgus69P5mDJyI1SUrQd8039BrPnIfDrA96MBCVoqxCl3JCFXuW37ziBnMexcGcZauqK9eAppyRAQxmNID4sohtbMujh/zO3/0f44F3oTfYAn7QWDJbadmZC/kG5WcXw1aw+XoM7klBTP+c5XZRr7/5Z3s9pDktRL7G6+T+Z3zAoGAT0RWFgjbejYAIqQeAM0ytoAZvP22XMLNcJpYubpK8mh2VeHqOfcFgKofG5fySw6kN1AG83PsWmQ7bD8jwcR14QG4vxaHzU95d0E3Bs6a5DsO1lnEolgtmTjDK9K31eLOq1bZlV5LePqCNB9gREE5lOkFpJiCtmic5o/VMETl/iMCgYEAwFw4ahes2Rj8ENksEe4zBFun0yZfYt1PrnoAq0mZvNMahd3ZKPmFhQX2ukVYQC8Y52Pvhxag7cZoOYtCgB5Y7TjIKS3lp+GqVigODZBPThXEdnqFC4mSkEoG1/A4ZEj1nGI8oBuggNvTSDZBQAdPxy8JfRk5llO//B2DfgN+sTg=}
